# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rain',
            name='id',
        ),
        migrations.AlterField(
            model_name='rain',
            name='station',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
