# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raindata',
            old_name='prcpDate',
            new_name='ddate',
        ),
        migrations.RemoveField(
            model_name='raindata',
            name='RDID',
        ),
    ]
